# Generated by Django 3.2.6 on 2021-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_salary', models.IntegerField()),
                ('emp_city', models.CharField(max_length=50)),
            ],
        ),
    ]
